<head>
    <link rel="stylesheet" href="/css/style3.css">
</head>
<div class="container">
    <form action="/consulta" method="POST">
        <label for="">Digite o email de quem deseja consultar</label>
        <input type="text" class="form-control" name="email" id="email">
        <button type="submit" style="margin-top: 1em;" class="btn btn-success btn-lg btn-block">Consultar</button>
    </form>

    <a href="/"><button style="margin-top: 0.5em;" type="button" class="btn btn-secondary btn-lg btn-block">Voltar</button></a>
</div>