<head>
    <link rel="stylesheet" href="/css/style2.css">
</head>

<div class="container">
    <form action="/registrar" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="foto">Escolha uma foto</label>
            <input type="file" class="form-control-file" id="foto" name="foto">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" id="nome" placeholder="Nome" name="nome" value="<?= $this->view->user['nome'] ?>">
            </div>

            <div class="form-group col-md-6">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Email" name="email" value="<?= $this->view->user['email'] ?>">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="cidade">Cidade</label>
                <input type="text" class="form-control" id="cidade" name="cidade" value="<?= $this->view->user['cidade'] ?>">
            </div>

            <div class="form-group col-md-4">
                <label for="estado">Estado</label>
                <select id="estado" class="form-control" name="estado">
                    <option selected>DF</option>
                    <option>SP</option>
                    <option>MG</option>
                    <option>RJ</option>
                </select>
            </div>

            <div class="form-group col-md-2">
                <label for="cep">CEP</label>
                <input type="text" class="form-control" id="cep" name="cep" value="<?= $this->view->user['cep'] ?>">
            </div>
        </div>

        <div id="add-form">
            <div class="group-form">
                <label for="">Telefone</label>
                <button class="btn btn-add" type="button" id="add"><i class="fas fa-plus"></i></button>
            </div>
        </div>


        <button type="submit" class="btn btn-success">Cadastrar</button>
        <?php if($this->view->erroCadastro) { ?>
            <small class="form-text text-danger">Erro ao realizar cadastro!</small>
        <?php } ?>
    </form>
</div>

<script>
    var cont = 1;

    $("#add").click(function() {
        $("#add-form").append('<div class="group-form" id="campo'+cont+'"><input type="text" class="form-control col-md-4" id="fone" name="fone'+cont+'"><button class="btn btn-add apagar" type="button" id="'+ cont+ '"><i class="fas fa-minus"></i></button></div>');
        cont++;
    });

    $("#add-form").on("click", ".apagar", function() {
        var button_id = $(this).attr("id");
        $('#campo' + button_id + '').remove();
    });
</script>