<head>
    <link rel="stylesheet" href="/css/style2.css">
</head>

<div class="container">
    <form action="/registrar" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="foto">Escolha uma foto</label>
            <input type="file" class="form-control-file" id="foto" name="foto">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="nome">Nome</label>
                <input type="text" class="form-control" id="nome" placeholder="Nome" name="nome">
            </div>

            <div class="form-group col-md-6">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Email" name="email">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="cidade">Cidade</label>
                <input type="text" class="form-control" id="cidade" name="cidade">
            </div>

            <div class="form-group col-md-4">
                <label for="estado">Estado</label>
                <select id="estado" class="form-control" name="estado">
                    <option selected>DF</option>
                    <option>SP</option>
                    <option>MG</option>
                    <option>RJ</option>
                </select>
            </div>

            <div class="form-group col-md-2">
                <label for="cep">CEP</label>
                <input type="text" class="form-control" id="cep" name="cep">
            </div>
        </div>

        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>
</div>