<head>
    <link rel="stylesheet" href="/css/style3.css">
</head>

<div class="container">
    <h1>Victor Hugo Campos de Oliveira</h1>
    <img src="/img/home.png/" alt="Foto Ilustrativa">
    <div>
        <label for="email">Email</label>
        <h2 name="email">xxxxxxxxxxx@gmail.com</h2>
        <label for="cidade">Cidade</label>
        <h2 name="cidade">Brasília</h2>
        <label for="estado">Estado</label>
        <h2 name="estado">DF</h2>
        <label for="cep">CEP</label>
        <h2 name="cep">71710-560</h2>
    </div>

    <a href="/"><button type="button" class="btn btn-secondary btn-lg btn-block">Voltar</button></a>
</div>