<head>
    <link rel="stylesheet" href="/css/style.css">
</head>

<div class="container">

    <h1 class="titulo">Cadastro de Pessoas</h1>
    <img src="/img/home.png/" alt="Foto Ilustrativa">
    <div class="group">
        <a href="/cadastrar"><button type="button" class="btn btn-success btn-lg btn-block">Cadastrar</button></a>
        <a href="/busca"><button type="button" class="btn btn-secondary btn-lg btn-block">Consultar</button></a>
    </div>

</div>
